package com.sdkj.dataobject;

public class PaymentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.id
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.serial
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    private String serial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.id
     *
     * @return the value of payment.id
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.id
     *
     * @param id the value for payment.id
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.serial
     *
     * @return the value of payment.serial
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.serial
     *
     * @param serial the value for payment.serial
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }
}