package com.sdkj.dao;

import com.sdkj.dataobject.PaymentDO;

public interface PaymentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    int insert(PaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    int insertSelective(PaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    PaymentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    int updateByPrimaryKeySelective(PaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 19 08:36:22 CST 2022
     */
    int updateByPrimaryKey(PaymentDO record);
}