# 端口
server:
  port: 8006

spring:
  application:
    name: cloud-order
  cloud:
    consul:
      host: 192.168.186.128
      port: 8500
      discovery:
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}