server:
  port: 8889
eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka3.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: false
    #Eureka Server交互地址
    service-url:
      #修改为集群模式：设置服务中心地址，指向其他注册中心
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka1.com:8887/eureka,http://${spring.security.user.name}:${spring.security.user.password}@eureka2.com:8888/eureka
spring:
  application:
    name: cloud-eureka-server3
  security:
    user:
      name: root
      password: root